runtime/rocker: Add more validation
In some cases we are getting exception on kci-easy, if docker image
doesn't exist:

Image local/staging-gcc-10:riscv64-kselftest-kernelci not found on docker hub, using local
Image local/staging-gcc-10:riscv64-kselftest-kernelci not found
03/20/2024 09:00:12 AM UTC [ERROR] Traceback (most recent call last):
  File "/home/kernelci/pipeline/base.py", line 69, in run
    status = self._run(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/kernelci/./pipeline/scheduler.py", line 167, in _run
    self._run_job(job, runtime, platform, input_node)
  File "/home/kernelci/./pipeline/scheduler.py", line 135, in _run_job
    job_id = str(runtime.get_job_id(running_job))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kernelci/runtime/docker.py", line 119, in get_job_id
    return job_object.id
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

Traceback (most recent call last):
  File "/home/kernelci/./pipeline/scheduler.py", line 192, in <module>
    status = opts.command(configs, opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kernelci/./pipeline/scheduler.py", line 185, in __call__
    return Scheduler(configs, args).run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kernelci/pipeline/base.py", line 76, in run
    self._stop(context)
  File "/home/kernelci/./pipeline/scheduler.py", line 73, in _stop
    self._cleanup_paths()
  File "/home/kernelci/./pipeline/scheduler.py", line 58, in _cleanup_paths
    job_tmp_dirs = {
                   ^
  File "/home/kernelci/./pipeline/scheduler.py", line 62, in <dictcomp>
    if job.poll() is None
       ^^^^^^^^

We can handle it better.

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>